### ISSUE TITLE
JsonDiff bug found

### ISSUE THREAD

**Issue by fmoghaddam** [flipkart-incubator/zjsonpatch#187]
## Expected Behavior
**Source:**
```
{
    "store": {
        "a": [
            "v1",
            "v2"
        ]
    }
}
```

**Target:**
```
{
    "store": {
        "a": []
    }
}
```

running `JsonDiff.asJson(source, target)` should return:

```
[
    {
        "op": "remove",
        "path": "/store/a/0",
        "value": "v1"
    },
    {
        "op": "remove",
        "path": "/store/a/1",
        "value": "v2"
    }
]
```

## Actual Behavior

But returns:

```
[
    {
        "op": "remove",
        "path": "/store/a/0",
        "value": "v1"
    },
    {
        "op": "remove",
        "path": "/store/a/0",
        "value": "v2"
    }
]
```

## Steps to Reproduce the Problem
running `JsonDiff.asJson(source, target)`
## Specifications
Maven
Windows

Library Version:  0.4.16
Language (e.g. Java 1.8, Scala, etc): Java 17

**Comment by abhinavgemawat** [comment]
This is expected behaviour and patch generated by zjsonpatch is correct. This behaviour arises from the remove operation in JSON patch. When an item is removed, the subsequent item shift left to fill the gap in the array, which changes the indices. In your case, after removing the first element “v1” at 0 index, the second element “v2” shifts left and takes index 0. Thus, to remove “v2” the operation will also target index 0. The array indices are dynamic and adjust as elements are added and removed.

https://datatracker.ietf.org/doc/html/rfc6902#section-4.2
"If removing an element from an array, any elements above the
   specified index are shifted one position to the left."
