### ISSUE TITLE
How do I access the source and target values in a reported diff between 2 jsons?

### ISSUE THREAD

**Issue by sudhak271** [flipkart-incubator/zjsonpatch#27]
I'm trying to find the diff between two JSON objects using zjsonpatch. However, I want the results to return the source as well as the target values of the changed object. For example, the following:

    ObjectMapper mapper = new ObjectMapper();

    JsonNode source = null;
    JsonNode revised = null;
    try {
        source = mapper.readTree("{\"a\":1, \"b\":2}");
        revised = mapper.readTree("{\"a\":1, \"b\":3}");
    } catch (IOException e) {
        e.printStackTrace();
    }
    JsonNode patch = JsonDiff.asJson(source, revised);

will return

[{"op":"replace","path":"/b","value":3}]

This is essentially how it changed, where it changed, and what the new value is. I want it to include the original value from source (in this case, it would be 2). Is there a way of me accessing this value? The data set has the potential of being very large.

**Comment by holograph** [comment]
JSON Patch payloads are not reversible (i.e. they don't carry the data
you're missing, at least not by design).

It might be possible to carry this data along by extending the RFC schema,
but this isn't standard and will only be supported by this library. What I
would advise instead is to always calculate a reverse diff and store both
payloads; this is easy to implement and does not require specialized
library support.

**Comment by chetanti** [comment]
@sudhak271, were you able to get source value as well in diff result ?
If yes, can you please help me with solution , i am also having something similar need.

**Comment by cyruscabreracwt** [comment]
Don't know if this still helps, but adding a Diff Flag will return the original value.

![image](https://user-images.githubusercontent.com/92498430/161659011-40bc78db-43ec-4f93-8c63-b367dc91064d.png)
