### ISSUE TITLE
JsonDiff.asJson 'replace' ops are reversed.

### ISSUE THREAD

**Issue by marcosscriven** [flipkart-incubator/zjsonpatch#29]
I *think* there's an issue with the output of ```JsonDiff.asJson```.  

While the ```add``` and ```remove``` ops are as expected, the ```replace``` op seems to have the ```source``` value, rather than the ```target``` value.

A simple workaround to this is reverse the arguments, and reverse the meaning of ```add``` and ```remove```.

**Comment by vishwakarma** [comment]
Hi 
The replace operation ( diff generated ) have following components -
1. path
2. value ( which is target's value)

Is there anything am i missing here ?
Can you please quote an example for same ?

Thank you

**Comment by marcosscriven** [comment]
Wow @vishwakarma - fast response. I should say, thanks for this library, saved me a lot of time.

I'm confused why the ```replace``` op provides the target's _current_ value? I thought the point of the diff was to be able to take the original source, and apply the diff? If the diff contains the target's current value that's not possible.

As I say, if I reverse the args, then the ```replace``` op does give me the source's value, which would need to replace the target's value.

**Comment by marcosscriven** [comment]
Ah - I'm sorry about this. I see now the behaviour is correct.

**Comment by vishwakarma** [comment]
Actually as per the RFC, following equation hold -
 **source + diff = target**

So, in case of replace operation, diff will have with what value the replace should happen so that it becomes equivalent to target.
Example : 
sourceJson => {"compare":"c"}
targetJson => {"compare":"d"}
Diff => [{"op":"replace","path":"/compare","value":"d"}]

Now, if we apply diff on top of sourceJson, then we ill get the targetJson.

**Comment by marcosscriven** [comment]
Yes, that makes sense. Thanks again for your work.
