### ISSUE TITLE
Run custom code while applying a patch

### ISSUE THREAD

**Issue by manhhavu** [flipkart-incubator/zjsonpatch#36]
I'm looking for a mechanism allowing to run custom code while applying a patch to a JSON document. 

My use case (simplified) is following:
* I have complex documents (in XML) that I need to keep in sync with an external system (that I don't have control). 
* Suppose that a document has following structure:
```
document:
- forward
- preface
- chapters:
   - name: Chapter 1
     sections:
     - name: Section 1
       paragraphs:
         - id: 1
            content: Some arbitrary text
...
```
* Sometime, I have to update a document then synchronise it with the external system. However, this external system does not allow me to update the document in one shot but only partially in a request. I can call multiple its web services to update each part of the document, then finally, I can confirm the  previous changes or abort. An exemple of its web services is:

```
- startEditing()
- updatePreface(id, content, ...)
- updateSection(id, name, ...)
- updateParagraph(id, content, ...)
- confirmChanges()
- abortChanges()
```
* To minimise number of requests sending to the external system, I intend to convert a original document to JSON, compare them with its modified version to generate a JSON patch. While applying the patch, I will map each patch operation (add/remove/replace,...) to a web service of external system.

I've look at the code, specifically [JsonPatch](https://github.com/flipkart-incubator/zjsonpatch/blob/0.3.1/src/main/java/com/flipkart/zjsonpatch/JsonPatch.java) and [ApplyProcessor](https://github.com/flipkart-incubator/zjsonpatch/blob/0.3.1/src/main/java/com/flipkart/zjsonpatch/ApplyProcessor.java). It seems that there are not yet a way to inject a custom JsonPatchProcessor or some kind of listener/hook in this library. I wonder if you intend to add this functionality any time soon? Or if you see another ways to implement my use case, it will be great too.

Thanks for your help.

**Comment by vishwakarma** [comment]
Hi @manhhavu 
Apologies for such late response.

Unfortunately, currently there is no support for running custom code in this library.

As i understood, you need a support of preview after patch Operation, and then there we can decide wether to apply or abort the patch. One way to build is to apply the patch on copy of target json document and save that state. Once user confirms the changes ( preview ), we can then actually persist that state of json,  provided that Json hasn't been modified meanwhile OR Abort the state accordingly. This needs to be built on top of this library, since currently each operation of this library is stateless.
We can discuss more on this, lets connect offline of github @ ( vishwakarma.iiita@gmail.com )

**Comment by manhhavu** [comment]
Thank @vishwakarma for your explanation.

It was correct, your understanding of my requirement. I'm currently assessing **zjsonpatch** and some other approches. I will get back to you if I have any further questions.

I close this issue now as my question was answered.

**Comment by vishwakarma** [comment]
Sure, please feel free to contact me.
