### ISSUE TITLE
copy/replace in one patch doc

### ISSUE THREAD

**Issue by amarchewka** [flipkart-incubator/zjsonpatch#64]
If I start with the following JSON doc:
`{"profiles":{"abc":[],"def":[{"hello":"world"}]}}`

and apply the following patch:
`[{"op":"copy","from":"/profiles/def/0", "path":"/profiles/def/0"},{"op":"replace","path":"/profiles/def/0/hello","value":"world2"}]`

I get the following output:
`{"profiles":{"abc":[],"def":[{"hello":"world2"},{"hello":"world2"}]}}`

That is, the "replace" operation was applied to both array elements.
(Or possibly, the "replace" was applied before the "copy".)

Applying the "copy" and then the "replace" in 2 separate patch docs works as expected.

The following on-line tool [https://json-schema-validator.herokuapp.com/jsonpatch.jsp]
agrees the original output should have been
`{"profiles":{"abc":[],"def":[{"hello":"world2"},{"hello":"world"}]}}`
with the "replace" applied only to array element 0.

Thanks for a great library, btw!

**Comment by luliu** [comment]
I noticed in `InPlaceApplyProcessor`'s `copy` function, the same `valueNode` object is assigned to the `toPath`:  

https://github.com/flipkart-incubator/zjsonpatch/blob/af15e01024e94a0afe9377b9d9e54e246dfe91e8/src/main/java/com/flipkart/zjsonpatch/InPlaceApplyProcessor.java#L53-L59

Is this a bug? As any mutation done to the source `JsonNode` in the same batch of patch operations  will affect the target since they're the same object.

Here's an example:
---
Original document:
```
{"top": {"object1": {"key1":"val1","key2":"val2"}, "object2":"-----"}
```
Patch:
```
[
{"op":"copy", "from":"/top/object1", "path":"/top/object2"},
{"op":"replace","path":"/top/object1/key1","value":"++++"}
]
```
Result:
```
{"top": {"object1": {"key1":"++++","key2":"val2"}, "object2": {"key1":"++++","key2":"val2"}}}
```

__Note__ that both `object1` and `object2`'s `key1` changed to `++++`.

**Comment by vishwakarma** [comment]
@luliu @amarchewka 
Agreed, this certainly looks like a bug ( Using copy by reference instead of copy by value ), i will go deeper into the code and will fix the issue by this week.
Thank you for raising the issue.

**Comment by amarchewka** [comment]
That's great.  Thanks!

**Comment by vishwakarma** [comment]
The bug is fixed, Closing the issue.

Thanks again for raising the issue.
