### ISSUE TITLE
Option for marking a variable as "Not Patchable"

### ISSUE THREAD

**Issue by danieldonev** [flipkart-incubator/zjsonpatch#76]
First of all - Amazing project. 
Works really fast and it is easy to use.

I am missing just one functionality. 

It would be really good (since it uses Jackson beneath) to add @Anotation for marking variables as "Not patchable".

So if patch attempt is made on variable marked with (for ex.) @DisablePatch - the patch function will throw an exception.

Is such thing possible ?

Thank you in advance.

**Comment by vishwakarma** [comment]
Hi @danieldonev,  Thanks for writing in.

Please share your thoughts on following --
1. Can you please share a real-life use-case as per your product, if applicable? 
2. What are other Annotations support required to be supported?
3. While generating Diff/Patch, should algorithm honor the annotations like - do not generate diff on the variable with @DisablePatch, because if we don't honor them then generated Patch will always be inconsistent and can't be applied on the source json.

**Comment by danieldonev** [comment]
Hey @vishwakarma 
1. In my `Account` class there is properties such as `password` and`tempPassword ` variables which must not be patched, but properties as `email` or `name` can be.

2. Sorry but I don't understand the question :(

3. If you try to patch a variable decorated with the @anotation in question - the patch method should throw an exception with something like - "Can not patch variable with decorated with @DisablePatch" and the patch should be cancelled.

**Comment by danieldonev** [comment]
Any idea if this is possible?

**Comment by vishwakarma** [comment]
Hi @danieldonev, Apologies for getting back so late on this.
The changes requested are currently beyond the scope of this RFC implementation.
